---
env:
  PANTS_CONFIG_FILES: "['pants.toml', 'pants.ci.toml']"
  BUILDKITE_PLUGIN_VAULT_ENV_SECRET_PREFIX: "secret/data/buildkite/env"

steps:
  - label: ":cloudsmith::docker: Upload new Cloudsmith container"
    command:
      - make image-push
    plugins:
      - grapl-security/vault-login#v0.1.0
      - grapl-security/vault-env#v0.1.0:
          secrets:
            - CLOUDSMITH_API_KEY
      - docker-login#v2.0.1:
          username: grapl-cicd
          password-env: CLOUDSMITH_API_KEY
          server: docker.cloudsmith.io
    agents:
      queue: "docker"

  - wait

  # Re-run validation with the new image, just to be safe.

  - label: ":cloudsmith::docker: Upload testing container"
    key: test-upload
    command:
      - docker buildx bake merge-move-image --file=docker-bake.testing.hcl --push
    plugins:
      - grapl-security/vault-login#v0.1.0
      - grapl-security/vault-env#v0.1.0:
          secrets:
            - CLOUDSMITH_API_KEY
      - docker-login#v2.0.1:
          username: grapl-cicd
          password-env: CLOUDSMITH_API_KEY
          server: docker.cloudsmith.io
    agents:
      queue: "docker"

  - label: ":cloudsmith::buildkite: Promotion Test (move)"
    key: promotion-test
    depends_on: test-upload
    plugins:
      - grapl-security/vault-login#v0.1.0
      - grapl-security/vault-env#v0.1.0:
          secrets:
            - CLOUDSMITH_API_KEY
      - grapl-security/cloudsmith#${BUILDKITE_COMMIT}:
          # See contents of the `merge-move-image` target in
          # `docker-bake.testing.hcl` for where these values come from.
          promote:
            # Use the image we just built to drive this
            image: docker.cloudsmith.io/grapl/raw/cloudsmith-cli
            tag: latest
            org: grapl
            from: testing-stage1
            to: testing-stage2
            packages:
              cloudsmith-buildkite-plugin-merge-move-test: ${BUILDKITE_BUILD_ID}
    agents:
      queue: "docker"  # could also be artifact-uploaders

  - label: ":cloudsmith::white_check_mark: Verify Promotion (move)"
    key: verify-promotion
    depends_on: promotion-test
    command:
      - .buildkite/scripts/verify_promotion.sh "cloudsmith-buildkite-plugin-merge-move-test" "move"
    plugins:
      - grapl-security/vault-login#v0.1.0
      - grapl-security/vault-env#v0.1.0:
          secrets:
            - CLOUDSMITH_API_KEY
    agents:
      queue: "docker"

  - wait

  - label: ":cloudsmith::buildkite: Promote new cloudsmith-cli image"
    plugins:
      - grapl-security/vault-login#v0.1.0
      - grapl-security/vault-env#v0.1.0:
          secrets:
            - CLOUDSMITH_API_KEY
      - grapl-security/cloudsmith#v0.1.0:
          promote:
            org: grapl
            from: raw
            to: releases
            packages:
              cloudsmith-cli: latest
    agents:
      queue: "docker"
