env:
  PANTS_CONFIG_FILES: "['pants.toml', 'pants.ci.toml']"
  BUILDKITE_PLUGIN_VAULT_ENV_SECRET_PREFIX: "secret/data/buildkite/env"

steps:
  - label: ":jeans: All files are covered by Pants"
    command:
      - ./pants tailor --check

  - label: ":lint-roller::bash: Lint Shell"
    command:
      - make lint-shell
    plugins:
      - grapl-security/vault-login#v0.1.2
      - grapl-security/vault-env#v0.1.0:
          secrets:
            - cloudsmith-buildkite-plugin/TOOLCHAIN_AUTH_TOKEN

  - label: ":lint-roller::docker: Lint Dockerfiles"
    command:
      - make lint-docker
    plugins:
      - grapl-security/vault-login#v0.1.2
      - grapl-security/vault-env#v0.1.0:
          secrets:
            - cloudsmith-buildkite-plugin/TOOLCHAIN_AUTH_TOKEN

  - label: ":lint-roller: Lint HCL"
    command:
      - make lint-hcl

  - label: ":lint-roller::buildkite: Lint Plugin"
    command:
      - make lint-plugin

  - label: ":bash: Unit Test Shell"
    command:
      - make test-shell
    plugins:
      - grapl-security/vault-login#v0.1.2
      - grapl-security/vault-env#v0.1.0:
          secrets:
            - cloudsmith-buildkite-plugin/TOOLCHAIN_AUTH_TOKEN

  - label: ":buildkite::bash: Unit Test Plugin"
    command:
      - make test-plugin

  - label: ":docker: Build Image"
    command:
      - make image

  ########################################################################

  - wait

  - label: ":pipeline: Testing the 'move' promotion"
    command:
      - ".buildkite/pipeline.plugin-test.sh move | buildkite-agent pipeline upload"

  - label: ":pipeline: Testing the 'copy' promotion"
    command:
      - ".buildkite/pipeline.plugin-test.sh copy | buildkite-agent pipeline upload"
