---
env:
  PANTS_CONFIG_FILES: "['pants.toml', 'pants.ci.toml']"
  BUILDKITE_PLUGIN_VAULT_ENV_SECRET_PREFIX: "secret/data/buildkite/env"

steps:
  - label: ":bash: Linting"
    command:
      - "./pants lint ::"
    plugins:
      - grapl-security/vault-login#v0.1.0
      - grapl-security/vault-env#v0.1.0:
          secrets:
            - buildkite-common/TOOLCHAIN_AUTH_TOKEN

  - label: ":bash: Testing"
    command:
      - "./pants test ::"
    plugins:
      - grapl-security/vault-login#v0.1.0
      - grapl-security/vault-env#v0.1.0:
          secrets:
            - buildkite-common/TOOLCHAIN_AUTH_TOKEN
